name: RenderCloud
favicon: null
typography_spectrum: 0.608108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#88A0A8'
    - '#104050'
    - '#6890A0'
    - '#C8B038'
    - '#D8D098'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
