name: RenderCloud
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#6088A0'
    - '#000000'
    - '#A0C0D8'
  brandStrength: 1
  lightness: 0.493243
  saturation: 1
  rhythmicContrast: 0.497466
purpose: []
