analytics: {}
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#6088A0'
    - '#000000'
    - '#A0C0D8'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.387668
name: RenderCloud
opengraph: {}
purpose: []
typography_spectrum: 0
