name: RenderCloud
favicon: null
layout_spectrum: 0.25585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0702'
    - '#173034'
    - '#5f5a3a'
    - '#f8a82b'
    - '#0c6a80'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
