name: RenderCloud
favicon: null
typography_spectrum: 0.608108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#d7d7d7'
    - '#4a4a4a'
    - '#787878'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
